[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc_rust_2022"
path = "src/main.rs"

[lib]
name = "aoc_rust_2022"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
regex = "1.7.0"
